const express = require('express');
const router = express.Router();
const { getlisteclient,getlisteclientsfilter,AjouterClient, supprimerClient, getClient, updateClient } = require('../controllers/clientController');
router.get("/:dbName/List",getlisteclient);
router.get("/:dbName/filterClient",getlisteclientsfilter);
router.get("/:dbName/Get/:code", getClient);
router.post("/:dbName/Add",AjouterClient);
router.delete("/:dbName/Delete", supprimerClient);
router.put("/:dbName/Update", updateClient);
module.exports = router;