const clientInfoInitiales = {
  code: "",
  rsoc: "",
  cp: "",
  matemaj: "",
  adresse: "",
  email: "",
  telephone: "",
  tel1: "",
  tel2: "",
  datcreat: new Date().toISOString().split("T")[0],
  telex: "",
  desrep: "",
  aval2: "",
  aval1: "",
  Commentaire: "",
  datemaj: "",
  userm: "",
  usera: "",
  // ? les champs suivantes sont des checkboxes
  // ? on initialise leurs valeurs à 0 pour dire
  // ? que initialement ils sont décochés
  offretick: "0",
  timbref: "0",
  cltexport: "0",
  suspfodec: "0",
  regime: "0",
  exon: "0",
  majotva: "0",
  fidel: "0",
  ptva: "0",
  // ? =========================================
  // ? les champs suivantes sont des selects
  // ? on initialise leurs valeurs à 0 pour dire
  // ? Non (N)
  blockage: "0",
  contrat: "0",
  // ? ==========================================
  datefinaut: "",
  datedebaut: "",
  decision: "",
  matriculef: "",
  reference: "",
  srisque: "",
  scredit: "",
  delregBL: "",
  delregFT: "",
  delregFC: "",
  remise: "",
  activite: "",
  typecli: "L",
  cin: "",
  fax: "",
  codes: "",
  coder: "",
  codesec: "",
  desisec: "",
  codergg: "",
  desirgg: "",
  desicp: "",
  nom1: "",
  nom2: "",
  nom3: "",
};
