const dateCourant = new Date().toISOString().split("T")[0];

const devisInfoInitiales = {
  NUMBL: "",
  libpv: "SIEGE LOCAL",
  ADRCLI: "",
  CODECLI: "",
  delailivr: "",
  modepaie: "",
  transport: "",
  numPage: 1,
  cp: "",
  DATEBL: dateCourant,
  MREMISE: 0,
  MTTC: 0,
  MTVA: 0,
  comm: "",
  CODEREP: "",
  RSREP: "",
  CODEREP: "",
  TIMBRE: 0,
  usera: "",
  userm: "",
  RSCLI: "",
  codesecteur: "",
  MHT: 0,
  email: "",
  REFCOMM: "",
  desisec: "",
  DATEDMAJ: dateCourant,
  articles: [],
};
